-- =============================================
-- Monalisa Nutrition — FRESH Data Migration Seed
-- Run this in phpMyAdmin AFTER running schema.sql
-- This seed uses strictly sanitized data and IDs
-- =============================================

-- First, clear the existing data!
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE `products`;
TRUNCATE TABLE `categories`;
SET FOREIGN_KEY_CHECKS = 1;

-- ---------------------------------------------
-- Insert Categories
-- ---------------------------------------------
INSERT INTO `categories` (`id`, `name`, `slug`, `description`, `image`) VALUES ('cat_promo', 'PROMO PACKS', 'packs', 'Exclusive curated bundles for ultimate results.', '/images/DORIANCRAETINE.webp');
INSERT INTO `categories` (`id`, `name`, `slug`, `description`, `image`) VALUES ('cat_whey', 'Whey Protein', 'whey-proteine', 'Rapid recovery and lean muscle building.', '/images/gold-standard-whey.webp');
INSERT INTO `categories` (`id`, `name`, `slug`, `description`, `image`) VALUES ('cat_gainers', 'Gainers', 'gainers', 'High-calorie formulas for serious mass and weight gain.', '/images/seriousmass.webp');
INSERT INTO `categories` (`id`, `name`, `slug`, `description`, `image`) VALUES ('cat_creatine', 'Creatine', 'creatine', 'Strength and power with pure monohydrate.', '/images/appliedcreatinemono.jpg');
INSERT INTO `categories` (`id`, `name`, `slug`, `description`, `image`) VALUES ('cat_amino', 'Amino Acids', 'acides-amines', 'Essential recovery aminos and EAA for muscle protection.', '/images/amino-1.webp');
INSERT INTO `categories` (`id`, `name`, `slug`, `description`, `image`) VALUES ('cat_preworkout', 'Pre-Workout', 'pre-workout', 'Energy and focus for your training.', '/images/c4ultimatepreworkout.webp');
INSERT INTO `categories` (`id`, `name`, `slug`, `description`, `image`) VALUES ('cat_vitamines', 'Vitamines', 'multivitamines', 'Complete daily nutrient support and wellness essentials.', '/images/animal-pak.webp');
INSERT INTO `categories` (`id`, `name`, `slug`, `description`, `image`) VALUES ('cat_accessories', 'Accessories', 'accessoires', 'High-quality gear and essentials for your fitness journey.', '/images/products/shaker-high-tech-quality.webp');

-- ---------------------------------------------
-- Insert Products
-- ---------------------------------------------
INSERT INTO `products` (`id`, `name`, `slug`, `brand`, `price`, `old_price`, `category`, `image`, `images`, `description`, `benefits`, `specs`, `is_rupture`) VALUES ('dp-17000000001', 'Gold Standard Whey Isolate', 'gold-standard-whey-isolate', 'Optimum Nutrition', 1199, 1300, 'whey-proteine', '/images/gold-standard-whey.webp', '["/images/gold-standard-whey.webp"]', 'The world''s most trusted protein, refined for the elite athlete.', '["24g Protein per serving","5.5g BCAA","Zero Sugar"]', '[{"label":"Weight","value":"2.27kg"}]', 0);
INSERT INTO `products` (`id`, `name`, `slug`, `brand`, `price`, `old_price`, `category`, `image`, `images`, `description`, `benefits`, `specs`, `is_rupture`) VALUES ('dp-17000000002', 'Nitro-Tech Elite', 'nitro-tech-elite', 'MuscleTech', 849, 999, 'whey-proteine', '/images/nitrotechelite.webp', '["/images/nitrotechelite.webp"]', 'Advanced muscle-building formula with creatine and amino acids.', '["30g Protein","3g Creatine","High Bioavailability"]', '[{"label":"Weight","value":"2.27kg"}]', 0);
INSERT INTO `products` (`id`, `name`, `slug`, `brand`, `price`, `old_price`, `category`, `image`, `images`, `description`, `benefits`, `specs`, `is_rupture`) VALUES ('dp-17000000003', 'Platinum Hydro Whey', 'hydro-whey', 'Optimum Nutrition', 829, 1000, 'whey-proteine', '/images/hydro-whey.webp', '["/images/hydro-whey.webp"]', 'Fastest absorbing protein.', '["Hydrolyzed Isolate"]', '[{"label":"Weight","value":"800g"}]', 0);
INSERT INTO `products` (`id`, `name`, `slug`, `brand`, `price`, `old_price`, `category`, `image`, `images`, `description`, `benefits`, `specs`, `is_rupture`) VALUES ('dp-17000000004', 'ISO 100 Hydrolysed Whey', 'iso-100', 'Dymatize', 949, 1200, 'whey-proteine', '/images/iso-100.webp', '["/images/iso-100.webp"]', 'Ultra-pure isolate.', '["Zero Fat","Low Carb"]', '[{"label":"Weight","value":"1.4kg"}]', 1);
INSERT INTO `products` (`id`, `name`, `slug`, `brand`, `price`, `old_price`, `category`, `image`, `images`, `description`, `benefits`, `specs`, `is_rupture`) VALUES ('dp-17000000005', 'Creatine Monohydrate Pure', 'creatine-pure', 'Applied Nutrition', 349, 400, 'creatine', '/images/appliedcreatinemono.jpg', '["/images/appliedcreatinemono.jpg"]', 'Pharmaceutical grade creatine.', '["5g Pure Creatine"]', '[{"label":"Servings","value":"50"}]', 0);
INSERT INTO `products` (`id`, `name`, `slug`, `brand`, `price`, `old_price`, `category`, `image`, `images`, `description`, `benefits`, `specs`, `is_rupture`) VALUES ('dp-17000000006', '100% Creatine Monohydrate', 'creatine-biotech', 'Biotech USA', 349, 400, 'creatine', '/images/creatine.webp', '["/images/creatine.webp"]', 'High quality creatine.', '["Pure Monohydrate"]', '[{"label":"Weight","value":"300g"}]', 0);
INSERT INTO `products` (`id`, `name`, `slug`, `brand`, `price`, `old_price`, `category`, `image`, `images`, `description`, `benefits`, `specs`, `is_rupture`) VALUES ('dp-17000000007', 'Creatine Gummies', 'creatine-gummies', 'Monalisa Edition', 299, 350, 'creatine', '/images/creatinegummies.webp', '["/images/creatinegummies.webp"]', 'Convenient and delicious creatine delivery.', '["No Water Needed","Great Taste"]', '[{"label":"Gummies","value":"60"}]', 0);
INSERT INTO `products` (`id`, `name`, `slug`, `brand`, `price`, `old_price`, `category`, `image`, `images`, `description`, `benefits`, `specs`, `is_rupture`) VALUES ('dp-17000000008', 'Serious Mass', 'serious-mass', 'Optimum Nutrition', 1099, 1200, 'gainers', '/images/seriousmass.webp', '["/images/seriousmass.webp"]', 'High-calorie weight gain formula.', '["1,250 Calories","50g Protein"]', '[{"label":"Weight","value":"5.44kg"}]', 0);
INSERT INTO `products` (`id`, `name`, `slug`, `brand`, `price`, `old_price`, `category`, `image`, `images`, `description`, `benefits`, `specs`, `is_rupture`) VALUES ('dp-17000000009', 'Big Monster Gainer', 'big-monster', 'Big Monster', 899, 1000, 'gainers', '/images/bigmonster.webp', '["/images/bigmonster.webp"]', 'Heavyweight mass building formula.', '["Massive Protein","Complex Carbs"]', '[{"label":"Weight","value":"5kg"}]', 0);
INSERT INTO `products` (`id`, `name`, `slug`, `brand`, `price`, `old_price`, `category`, `image`, `images`, `description`, `benefits`, `specs`, `is_rupture`) VALUES ('dp-17000000010', 'Super Gainer', 'super-gainer', 'Nutrition Plus', 799, 950, 'gainers', '/images/super-gainer.jpg', '["/images/super-gainer.jpg"]', 'Affordable and effective mass gainer.', '["High Calories","Easy Mixing"]', '[{"label":"Weight","value":"4kg"}]', 0);
INSERT INTO `products` (`id`, `name`, `slug`, `brand`, `price`, `old_price`, `category`, `image`, `images`, `description`, `benefits`, `specs`, `is_rupture`) VALUES ('dp-17000000011', 'Critical Mass Lean Gainer', 'critical-mass', 'Applied Nutrition', 949, 1100, 'gainers', '/images/critical-mass.webp', '["/images/critical-mass.webp"]', 'Lean mass building formula.', '["High Protein","Quality Carbs"]', '[{"label":"Weight","value":"6kg"}]', 0);
INSERT INTO `products` (`id`, `name`, `slug`, `brand`, `price`, `old_price`, `category`, `image`, `images`, `description`, `benefits`, `specs`, `is_rupture`) VALUES ('dp-17000000012', 'Mutant Mass Extreme 2500', 'mutant-mass-extreme', 'Mutant', 1149, 1300, 'gainers', '/images/mutantmassextrem2500.webp', '["/images/mutantmassextrem2500.webp"]', 'The ultimate hard gainer formula.', '["2500 Calories","High Protein"]', '[{"label":"Weight","value":"5.44kg"}]', 0);
INSERT INTO `products` (`id`, `name`, `slug`, `brand`, `price`, `old_price`, `category`, `image`, `images`, `description`, `benefits`, `specs`, `is_rupture`) VALUES ('dp-17000000013', 'C4 Ultimate Pre-Workout', 'c4-ultimate', 'Cellucor', 550, 650, 'pre-workout', '/images/c4ultimatepreworkout.webp', '["/images/c4ultimatepreworkout.webp"]', 'Explosive energy.', '["Extreme Energy"]', '[{"label":"Caffeine","value":"300mg"}]', 0);
INSERT INTO `products` (`id`, `name`, `slug`, `brand`, `price`, `old_price`, `category`, `image`, `images`, `description`, `benefits`, `specs`, `is_rupture`) VALUES ('dp-17000000014', 'Vapor X5 Pre-Workout', 'vapor-x5', 'MuscleTech', 599, 700, 'pre-workout', '/images/vapor-x5.webp', '["/images/vapor-x5.webp"]', 'Five-in-one pre-workout formula.', '["Neurosensory Experience","Explosive Energy"]', '[{"label":"Weight","value":"263g"}]', 0);
INSERT INTO `products` (`id`, `name`, `slug`, `brand`, `price`, `old_price`, `category`, `image`, `images`, `description`, `benefits`, `specs`, `is_rupture`) VALUES ('dp-17000000015', 'Amino 1', 'amino-1', 'MusclePharm', 449, 550, 'acides-amines', '/images/amino-1.webp', '["/images/amino-1.webp"]', 'Hydration and recovery formula.', '["BCAA 3:1:2 Ratio","Coconut Water"]', '[{"label":"Servings","value":"32"}]', 0);
INSERT INTO `products` (`id`, `name`, `slug`, `brand`, `price`, `old_price`, `category`, `image`, `images`, `description`, `benefits`, `specs`, `is_rupture`) VALUES ('dp-17000000016', 'EAA Zero', 'eaa-zero', 'Biotech USA', 399, 450, 'acides-amines', '/images/eaa-zero.webp', '["/images/eaa-zero.webp"]', 'Essential amino acids with no sugar.', '["Optimal EAA Ratio","Sugar Free"]', '[{"label":"Weight","value":"350g"}]', 0);
INSERT INTO `products` (`id`, `name`, `slug`, `brand`, `price`, `old_price`, `category`, `image`, `images`, `description`, `benefits`, `specs`, `is_rupture`) VALUES ('dp-17000000017', 'Animal Pak', 'animal-pak', 'Universal Nutrition', 649, 750, 'multivitamines', '/images/animal-pak.webp', '["/images/animal-pak.webp"]', 'The ultimate training pack.', '["Vitamins & Minerals","Performance Complex"]', '[{"label":"Packs","value":"44"}]', 0);
INSERT INTO `products` (`id`, `name`, `slug`, `brand`, `price`, `old_price`, `category`, `image`, `images`, `description`, `benefits`, `specs`, `is_rupture`) VALUES ('dp-17000000018', 'Pack Creatine Monohydrate Dorian Yates + Essentials', 'pack-creatine-dorian', 'Monalisa Special', 899, 1100, 'packs', '/images/DORIANCRAETINE.webp', '["/images/DORIANCRAETINE.webp"]', 'Complete muscle building pack.', '["Monohydrate","Multivitamins"]', '[{"label":"Includes","value":"Creatine + Vitamins"}]', 0);
INSERT INTO `products` (`id`, `name`, `slug`, `brand`, `price`, `old_price`, `category`, `image`, `images`, `description`, `benefits`, `specs`, `is_rupture`) VALUES ('dp-17000000019', 'Melatonin Extra 10mg 100 Capsules – Now food', 'melatonin-extra-10mg-100-capsules-now-food', 'Now Foods', 349, 500, 'multivitamines', '/images/products/melatonin-extra-10mg-100-capsules-now-food.webp', '["/images/products/melatonin-extra-10mg-100-capsules-now-food.webp"]', 'Bed time : ...', '["Date D’expiration : 04/2028 .","Ce produit aide à :","Favoriser un endormissement plus rapide.","Améliorer la qualité du sommeil et le repos nocturne.","Réduire les effets du décalage horaire (jet lag)."]', '[{"label":"Format","value":"Original"}]', 0);
INSERT INTO `products` (`id`, `name`, `slug`, `brand`, `price`, `old_price`, `category`, `image`, `images`, `description`, `benefits`, `specs`, `is_rupture`) VALUES ('dp-17000000020', 'Vitamin C1000 90 Capsules – Ostrovit', 'vitamin-c1000-90-capsules-ostrovit', 'Ostrovit', 249, 400, 'multivitamines', '/images/products/vitamin-c1000-90-capsules-ostrovit.webp', '["/images/products/vitamin-c1000-90-capsules-ostrovit.webp"]', '...', '["Date D’expiration : 04/2027 .","-Contribue au fonctionnement normal du système immunitaire.","-Aide à réduire la fatigue et l’épuisement.","-Protège les cellules contre le stress oxydatif.","-Participe à la formation normale du collagène (peau, os, cartilages, dents, gencives)."]', '[{"label":"Format","value":"Original"}]', 0);
INSERT INTO `products` (`id`, `name`, `slug`, `brand`, `price`, `old_price`, `category`, `image`, `images`, `description`, `benefits`, `specs`, `is_rupture`) VALUES ('dp-17000000021', 'BANDE DE POIGNET HIGH TECH QUALITY – BIOTECH', 'bande-de-poignet-high-tech-quality-biotech', 'Biotech USA', 49, 60, 'accessoires', '/images/products/bande-de-poignet-high-tech-quality-biotech.jpg', '["/images/products/bande-de-poignet-high-tech-quality-biotech.jpg"]', '...', '["Date d’éxpiration: 04/2027","Highlights :"]', '[{"label":"Format","value":"Original"}]', 0);
